import sys
import os

while True:
    if os.path.isfile("data"):
        f = open("data", "r")
        str1 = f.read().split()
        target = open("hackathonevent.ics", 'w')
        f.close()
        target.write("BEGIN:VCALENDAR")
        target.write("VERSION:2.0")
        target.write("PRODID:-//www.marudot.com//iCal Event Maker")
        target.write("X-WR-CALNAME:hackathon")
        target.write("CALSCALE:GREGORIAN")
        target.write("BEGIN:VTIMEZONE")
        target.write("TZID:America/New_York")
        target.write("TZURL:http://tzurl.org/zoneinfo-outlook/America/Havana")
        target.write("X-LIC-LOCATION:America/New_York")
        target.write("BEGIN:STANDARD")
        target.write("TZOFFSETFROM:-0400")
        target.write("TZOFFSETTO:-0500")
        target.write("TZNAME:CST")
        target.write("DTSTART:19701101T010000")
        target.write("RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU")
        target.write("END:STANDARD")
        target.write("BEGIN:DAYLIGHT")
        target.write("TZOFFSETFROM:-0500")
        target.write("TZOFFSETTO:-0400")
        target.write("TZNAME:CDT")
        target.write("DTSTART:19700308T000000")
        target.write("RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU")
        target.write("END:DAYLIGHT")
        target.write("END:VTIMEZONE")
        target.write("BEGIN:VEVENT")
        target.write("DTSTAMP:20160918T101557Z")
        target.write("UID:20160918T101557Z-857430515@marudot.com")
        target.write("DTSTART;TZID=\"America/New_York\":" + str1[0])
        target.write("DTEND;TZID=\"America/New_York\":" + str1[0])
        target.write("LOCATION:" + str1[1])
        target.write("END:VEVENT")
        target.write("END:VCALENDAR")
        target.close()

        os.remove("data")
